#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Feb 11 22:01:26 2018

@author: pavla
"""

COMPARISON_TYPE = 'rpmdiff'

STATE_NEW = 0
STATE_DONE = 1
STATE_STRINGS = {
    STATE_NEW: 'new',
    'new': STATE_NEW,
    STATE_DONE: 'done',
    'done': STATE_DONE,
}

CATEGORY_TAGS = 0
CATEGORY_PRCO = 1
CATEGORY_FILES = 2
CATEGORY_STRINGS = {
    CATEGORY_TAGS: 'tags',
    'tags': CATEGORY_TAGS,
    CATEGORY_PRCO: 'PRCO',
    'PRCO': CATEGORY_PRCO,
    CATEGORY_FILES: 'files',
    'files': CATEGORY_FILES,
}

DIFF_TYPE_REMOVED = 0
DIFF_TYPE_ADDED = 1
DIFF_TYPE_CHANGED = 2
DIFF_TYPE_RENAMED = 3
DIFF_TYPE_STRINGS = {
    DIFF_TYPE_REMOVED: 'removed',
    'removed': DIFF_TYPE_REMOVED,
    DIFF_TYPE_ADDED: 'added',
    'added': DIFF_TYPE_ADDED,
    DIFF_TYPE_CHANGED: 'changed',
    'changed': DIFF_TYPE_CHANGED,
    DIFF_TYPE_RENAMED: 'renamed',
    'renamed': DIFF_TYPE_RENAMED,
}

DIFF_STATE_IGNORED = 0
DIFF_STATE_NORMAL = 1
DIFF_STATE_ERROR = 2
DIFF_STATE_STRINGS = {
    DIFF_STATE_IGNORED: 'ignored',
    'ignored': DIFF_STATE_IGNORED,
    DIFF_STATE_NORMAL: 'normal',
    'normal': DIFF_STATE_NORMAL,
    DIFF_STATE_ERROR: 'error',
    'error': DIFF_STATE_ERROR,
}

TAGS = ('NAME', 'SUMMARY', 'DESCRIPTION', 'GROUP', 'LICENSE', 'URL',
        'PREIN', 'POSTIN', 'PREUN', 'POSTUN', 'PRETRANS', 'POSTTRANS')

PRCO = ('REQUIRES', 'PROVIDES', 'CONFLICTS', 'OBSOLETES',
        'RECOMMENDS', 'SUGGESTS', 'ENHANCES', 'SUPPLEMENTS')
